imba_project:
  outputs:
    dev:
      account: dg06331.ap-northeast-2.aws
      database: IMBA
      password: Yxyy820002176!
      role: SYSADMIN
      schema: dev
      threads: 1
      type: snowflake
      user: XICHEN
      warehouse: COMPUTE_WH
  target: dev